version: '3'

tasks:
  examples:
    cmds:
      - echo "Run a example like this, task examples:helloworld"
    silent: true

  examples:helloworld:
    desc: "Run basic helloworld app"
    cmds:
      - go run ./examples/helloworld/main.go

  examples:state:
    desc: "Run basic state app"
    cmds:
      - go run ./examples/state/main.go
