version: '3'

tasks:
    example-helloworld:
        cmds:
            - go run ./examples/helloworld/main.go
    example-states:
        cmds:
            - go run ./examples/state/main.go
    example-event:
        cmds:
            - go run ./examples/event/main.go
    example-substate:
        cmds:
            - go run ./examples/substate/main.go
