version: '3'

tasks:
  examples:
    cmds:
      - echo "Run a example like this, task examples:helloworld"
    silent: true

  examples:helloworld:
    desc: "Run basic helloworld app"
    cmds:
      - go run ./examples/helloworld

  examples:state:
    desc: "Run basic state app"
    cmds:
      - go run ./examples/state

  examples:substate:
    desc: "Run basic substate app"
    cmds:
      - go run ./examples/substate

  examples:signal:
    desc: "Run basic signal app"
    cmds:
      - go run ./examples/signal
